### ISSUE TITLE
Error after vagrant destroy and vagrant up

### ISSUE THREAD

**Issue by brndnu** [davidalger/m2demo#2]
user:~ user$ cd documents/m2demo
user:m2demo user$ vagrant destroy
    m2demo: Are you sure you want to destroy the 'm2demo' VM? [y/N] y
==> m2demo: Forcing shutdown of VM...
==> m2demo: Destroying VM and associated drives...
user:m2demo user$ vagrant up
Bringing machine 'm2demo' up with 'virtualbox' provider...
==> m2demo: Importing base box 'bento/centos-6.7'...
==> m2demo: Matching MAC address for NAT networking...
==> m2demo: Checking if box 'bento/centos-6.7' is up to date...
==> m2demo: Setting the name of the VM: M2Demo_m2demo_1484169782251_57414
==> m2demo: Clearing any previously set network interfaces...
==> m2demo: Preparing network interfaces based on configuration...
    m2demo: Adapter 1: nat
    m2demo: Adapter 2: hostonly
==> m2demo: Forwarding ports...
    m2demo: 22 (guest) => 2222 (host) (adapter 1)
==> m2demo: Running 'pre-boot' VM customizations...
==> m2demo: Booting VM...
==> m2demo: Waiting for machine to boot. This may take a few minutes...
    m2demo: SSH address: 127.0.0.1:2222
    m2demo: SSH username: vagrant
    m2demo: SSH auth method: private key
    m2demo: Warning: Remote connection disconnect. Retrying...
    m2demo: 
    m2demo: Vagrant insecure key detected. Vagrant will automatically replace
    m2demo: this with a newly generated keypair for better security.
    m2demo: 
    m2demo: Inserting generated public key within guest...
    m2demo: Removing insecure key from the guest if it's present...
    m2demo: Key inserted! Disconnecting and reconnecting using new SSH key...
==> m2demo: Machine booted and ready!
==> m2demo: Checking for guest additions in VM...
==> m2demo: Setting hostname...
==> m2demo: Configuring and enabling network interfaces...
==> m2demo: Installing rsync to the VM...
==> m2demo: Rsyncing folder: /Users/x/Documents/M2Demo/ => /vagrant
==> m2demo:   - Exclude: [".vagrant/", ".cache/"]
==> m2demo: Mounting shared folders...
    m2demo: /var/cache/npm => /Users/user/Documents/M2Demo/.cache/npm
    m2demo: /var/cache/yum => /Users/user/Documents/M2Demo/.cache/yum
    m2demo: /var/cache/composer => /Users/user/Documents/M2Demo/.cache/composer
==> m2demo: Running provisioner: shell...
    m2demo: Running: script: bootstrap.sh
**==> m2demo: :: running generic guest configuration
==> m2demo: :: configuring rpms needed for install
==> m2demo: https://mirror.steadfast.net/epel/6/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
==> m2demo: http://mirror.compevo.com/epel/6/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
==> m2demo: :: updating currently installed packages
==> m2demo: Error: Package: util-linux-ng-2.17.2-12.24.el6_8.1.x86_64 (updates)
==> m2demo:            Requires: kernel >= 2.6.32-642
==> m2demo:            Installed: kernel-2.6.32-573.el6.x86_64 (@anaconda-CentOS-201508042137.x86_64/6.7)
==> m2demo:                kernel = 2.6.32-573.el6
==> m2demo:                kernel = 2.6.32-573.el6
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.**

**Comment by davidalger** [comment]
@brndnu Hi! Sorry about the delay in responding, as I just now saw this. I have good news though :) I've fixed this issue in commit 3e4f988f85c. If you git pull to get the latest changes, then destroy and re-up your VM, it should work again.

Closing as resolved.
